### PR TITLE
fix(screenshot): wrong path for screenshots on Windows

### LINKED ISSUE #27: chrome and %5С
Добрый день! Не отображаются скриншоты в отчёте в браузере chrome: в url обратный слеш заменяется на %5C.
html-report

p.s.: корректно работает только в firefox.

### LINKED ISSUE #133: Wrong path to images.
I use configuration like in the documentation.
The problem is that images doesn't appear in html-reporter see attached picture.
I'm running `gemini gui`

```
module.exports = {
    // ...
    system: {
        plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: 'my/gemini-reports',
                defaultView: 'all',
                baseHost: 'test.com'
            }
        }
    },
    //...
}
```
gui report - google chrome 2018-07-11 18 33 59

### LINKED ISSUE #148: Не работают скриншоты в hermione-html-report
Если в конфиге hermione изменить путь до отчета:
```
  plugins: {
    'html-reporter/hermione': {
      path: 'tests/hermione/html-report',
    },
  }
```
То папка с отчетом создается, но при запуске hermione gui - страница не видит скриншоты. 
screenshot at 23 21-26-55

При исправлении пути на path: 'tests/hermione/**hermione-html-report**' репорт нормально показывает и принимает скриншоты.
screenshot at 23 21-27-22

### PR DESCRIPTION
**Pull request by sipayRT**
fix #133 
fix #27 
fix #148

### CODE REVIEW

**Comment by sipayRT** [comment]
//cc @DudaGod

File: test/unit/lib/static/components/section/screenshot.js [hunk 1]
```diff
@@ -5,6 +5,28 @@ import Placeholder from 'lib/static/components/state/placeholder';
...
+            <Screenshot image={{path: 'images/$/path'}} />,
+            {initialState: {view: {}}}
+        );
+
+        const image = screenshotComponent.find('img');
+
+        assert.equal(image.getDOMNode().src, 'images/%24/path');
+    });
+
+    it('should replace backslashes with slashes for screenshots', () => {
```
Comment (DudaGod) [inline test/unit/lib/static/components/section/screenshot.js:19]: with forward slashes, тогда уж =)

**Comment by sipayRT** [comment]
html-reporter@5.15.3
